### ISSUE TITLE
Unable to get gradle to do anything.

### ISSUE THREAD

**Issue by chibill** [PizzaCrust/Capiscum#1]
```
> C:\Users\chibi\Downloads\Capiscum-master\Capiscum-master>gradle tasks
Starting a Gradle Daemon, 1 busy and 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\chibi\Downloads\Capiscum-master\Capiscum-master\build.gradle' line: 37

* What went wrong:
A problem occurred evaluating root project 'Capsicum'.
> Could not read script 'C:\Users\chibi\Downloads\Capiscum-master\Capiscum-master\iodine-sdk\build.gradle' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 21.423 secs

```
This has to do with how the root build.gradle depends on iodine's but because iodine what not ran yet.  It does not exist to use as a dependency.

**Comment by PizzaCrust** [comment]
have you ran setupIodine

**Comment by chibill** [comment]
Fails with the same error.

**Comment by PizzaCrust** [comment]
i'll add a conditional to prevent this from happening

**Comment by PizzaCrust** [comment]
Commit e646f789421f0f755b25719f1b3edfda01aa5fe6 may fix the error.

**Comment by PizzaCrust** [comment]
this project is abandoned................................

gradle dependenciesm are crazzyz not circular depenendneicies

**Comment by PizzaCrust** [comment]
will refactor the whole project

**Comment by chibill** [comment]
Also on a side not iodine's patch system can't apply patches that it created.

**Comment by PizzaCrust** [comment]
it can i tested it

**Comment by chibill** [comment]
I keep getting hunk errors. And I have no idea why.

**Comment by PizzaCrust** [comment]
pls show your patch file

**Comment by chibill** [comment]
https://github.com/chibill/IodineFernflowerPatches thats them.... I generated them then made a fresh iodine thing and tried to apply them. (Maybe having it say which patch error-ed would be nice.)

**Comment by PizzaCrust** [comment]
Try using the latest version of Iodine, and if it comes with errors

**Comment by PizzaCrust** [comment]
report

**Comment by PizzaCrust** [comment]
or did you try using the latest

**Comment by chibill** [comment]
I was using the latest. (One you sent me.) going to try compiling a fresh one later.

**Comment by PizzaCrust** [comment]
ah ok, ive realized there is a major flaw in using gradle; it circulates since the project (api impl) depends on the project and the nms project compiles root project

**Comment by chibill** [comment]
Works now but now I have another problem.. That is rooted in Iodine.
